"""add sub-affiliate support

Revision ID: 02b8ba0cbb9f
Revises: f9f0f3d10ab8
Create Date: 2026-07-22 22:16:37.004531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02b8ba0cbb9f'
down_revision: Union[str, None] = 'f9f0f3d10ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_invites',
    sa.Column('parent_affiliate_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'revoked', name='invitestatus'), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('override_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_affiliate_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_affiliate_id'], ['affiliates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_affiliate_id'], ['affiliates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_invites_email'), 'affiliate_invites', ['email'], unique=False)
    op.create_index(op.f('ix_affiliate_invites_parent_affiliate_id'), 'affiliate_invites', ['parent_affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_invites_status'), 'affiliate_invites', ['status'], unique=False)
    op.create_index(op.f('ix_affiliate_invites_token'), 'affiliate_invites', ['token'], unique=True)
    op.add_column(
        'affiliate_commissions',
        sa.Column('source_affiliate_id', sa.Uuid(), nullable=True)
    )

    commission_type_enum = sa.Enum(
        'direct',
        'override',
        name='commissiontype'
    )
    commission_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'affiliate_commissions',
        sa.Column(
            'commission_type',
            commission_type_enum,
            nullable=False,
            server_default='direct'
        )
    )
    op.create_index(op.f('ix_affiliate_commissions_commission_type'), 'affiliate_commissions', ['commission_type'], unique=False)
    op.create_index(op.f('ix_affiliate_commissions_source_affiliate_id'), 'affiliate_commissions', ['source_affiliate_id'], unique=False)
    op.create_foreign_key(None, 'affiliate_commissions', 'affiliates', ['source_affiliate_id'], ['id'], ondelete='SET NULL')
    op.add_column('affiliates', sa.Column('sub_token', sa.String(length=64), nullable=True))
    op.add_column('affiliates', sa.Column('parent_affiliate_id', sa.Uuid(), nullable=True))
    op.add_column('affiliates', sa.Column('override_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.alter_column('affiliates', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_affiliates_parent_affiliate_id'), 'affiliates', ['parent_affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliates_sub_token'), 'affiliates', ['sub_token'], unique=True)
    op.create_foreign_key(None, 'affiliates', 'affiliates', ['parent_affiliate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'affiliates', type_='foreignkey')
    op.drop_index(op.f('ix_affiliates_sub_token'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_parent_affiliate_id'), table_name='affiliates')
    op.alter_column('affiliates', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('affiliates', 'override_rate')
    op.drop_column('affiliates', 'parent_affiliate_id')
    op.drop_column('affiliates', 'sub_token')
    op.drop_constraint(None, 'affiliate_commissions', type_='foreignkey')
    op.drop_index(op.f('ix_affiliate_commissions_source_affiliate_id'), table_name='affiliate_commissions')
    op.drop_index(op.f('ix_affiliate_commissions_commission_type'), table_name='affiliate_commissions')
    op.drop_column('affiliate_commissions', 'commission_type')

    commission_type_enum = sa.Enum(
        'direct',
        'override',
        name='commissiontype'
    )
    commission_type_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('affiliate_commissions', 'source_affiliate_id')
    op.drop_index(op.f('ix_affiliate_invites_token'), table_name='affiliate_invites')
    op.drop_index(op.f('ix_affiliate_invites_status'), table_name='affiliate_invites')
    op.drop_index(op.f('ix_affiliate_invites_parent_affiliate_id'), table_name='affiliate_invites')
    op.drop_index(op.f('ix_affiliate_invites_email'), table_name='affiliate_invites')
    op.drop_table('affiliate_invites')
    # ### end Alembic commands ###

