"""initial

Revision ID: 09315c06bdc6
Revises: 
Create Date: 2026-04-07 18:45:10.666889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09315c06bdc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_accounts',
    sa.Column('role', sa.Enum('DOCTOR', 'PATIENT', 'STAFF', name='userrole'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_user_accounts_role'), 'user_accounts', ['role'], unique=False)
    op.create_table('consultation_appointments',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_user_id', sa.Uuid(), nullable=True),
    sa.Column('patient_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'COMPLETED', 'CANCELLED', name='consultationstatus'), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=False),
    sa.Column('patient_gender', sa.String(length=50), nullable=True),
    sa.Column('patient_birth_date', sa.Date(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('appointment_mode', sa.String(length=50), nullable=False),
    sa.Column('treatment_plan', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('credit_cost', sa.Integer(), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_appointments_doctor_user_id'), 'consultation_appointments', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_consultation_appointments_owner_user_id'), 'consultation_appointments', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_consultation_appointments_patient_user_id'), 'consultation_appointments', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_consultation_appointments_status'), 'consultation_appointments', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_user_id', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_doctor_user_id'), 'conversations', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_patient_user_id'), 'conversations', ['patient_user_id'], unique=False)
    op.create_table('doctor_patients',
    sa.Column('doctor_user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='doctorpatientstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_user_id', 'patient_user_id')
    )
    op.create_index(op.f('ix_doctor_patients_doctor_user_id'), 'doctor_patients', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_doctor_patients_patient_user_id'), 'doctor_patients', ['patient_user_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('documents',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_user_id', sa.Uuid(), nullable=True),
    sa.Column('patient_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('TREATMENT_PLAN', 'XRAY', 'CONSENT_FORM', 'LAB_RESULT', 'PHOTO', 'INVOICE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doctor_user_id'), 'documents', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_owner_user_id'), 'documents', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_documents_patient_user_id'), 'documents', ['patient_user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('SIMULATION_READY', 'CONSULTATION_CONFIRMED', 'CONSULTATION_REMINDER', 'CONSULTATION_CANCELLED', 'CONSULTATION_RESCHEDULED', 'DOCUMENT_SHARED', 'STAFF_INVITE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('onboarding_sessions',
    sa.Column('role', sa.Enum('DOCTOR', 'PATIENT', 'STAFF', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'ACCOUNT_SAVED', 'PLAN_SELECTED', 'DETAILS_SAVED', 'COMPLETED', name='onboardingstatus'), nullable=False),
    sa.Column('current_step', sa.Enum('ACCOUNT', 'PLAN', 'DETAILS', 'COMPLETE', name='onboardingstep'), nullable=False),
    sa.Column('selected_plan', sa.Enum('STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='plancode'), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_onboarding_sessions_role'), 'onboarding_sessions', ['role'], unique=False)
    op.create_table('password_reset_token_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_sessions_token_hash'), 'password_reset_token_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_token_sessions_user_id'), 'password_reset_token_sessions', ['user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state_name', sa.String(length=120), nullable=False),
    sa.Column('state_code', sa.String(length=20), nullable=True),
    sa.Column('country_name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('zip_code', sa.String(length=30), nullable=False),
    sa.Column('preferred_contact_method', sa.Enum('SMS', 'EMAIL', 'PHONE', name='contactmethod'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payment_methods',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=20), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_is_default'), 'payment_methods', ['is_default'], unique=False)
    op.create_index(op.f('ix_payment_methods_stripe_payment_method_id'), 'payment_methods', ['stripe_payment_method_id'], unique=True)
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('refresh_token_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_token_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_sessions_token_hash'), 'refresh_token_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_sessions_user_id'), 'refresh_token_sessions', ['user_id'], unique=False)
    op.create_table('smile_simulations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_doctor_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('treatment_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'ACCEPTED', name='simulationstatus'), nullable=False),
    sa.Column('input_image_path', sa.Text(), nullable=False),
    sa.Column('output_image_path', sa.Text(), nullable=True),
    sa.Column('shade_preference', sa.String(length=100), nullable=True),
    sa.Column('smile_style', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_quality_score', sa.Integer(), nullable=False),
    sa.Column('ai_confidence_score', sa.Integer(), nullable=False),
    sa.Column('alignment_correction', sa.String(length=50), nullable=False),
    sa.Column('whitening_level', sa.String(length=50), nullable=False),
    sa.Column('smile_balance', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_doctor_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smile_simulations_created_by_doctor_id'), 'smile_simulations', ['created_by_doctor_id'], unique=False)
    op.create_index(op.f('ix_smile_simulations_status'), 'smile_simulations', ['status'], unique=False)
    op.create_index(op.f('ix_smile_simulations_user_id'), 'smile_simulations', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.Enum('STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='plancode'), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'UNPAID', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('simulations_used_this_period', sa.Integer(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('notify_email_consultations', sa.Boolean(), nullable=False),
    sa.Column('notify_email_simulations', sa.Boolean(), nullable=False),
    sa.Column('notify_email_documents', sa.Boolean(), nullable=False),
    sa.Column('notify_email_marketing', sa.Boolean(), nullable=False),
    sa.Column('notify_push_consultations', sa.Boolean(), nullable=False),
    sa.Column('notify_push_simulations', sa.Boolean(), nullable=False),
    sa.Column('notify_push_documents', sa.Boolean(), nullable=False),
    sa.Column('simulation_auto_send', sa.Boolean(), nullable=False),
    sa.Column('simulation_watermark', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('billing_transactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('invoice_url', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_transactions_status'), 'billing_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_billing_transactions_stripe_invoice_id'), 'billing_transactions', ['stripe_invoice_id'], unique=True)
    op.create_index(op.f('ix_billing_transactions_stripe_payment_intent_id'), 'billing_transactions', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_billing_transactions_subscription_id'), 'billing_transactions', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_transactions_user_id'), 'billing_transactions', ['user_id'], unique=False)
    op.create_table('clinics',
    sa.Column('doctor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('logo_name', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinics_doctor_profile_id'), 'clinics', ['doctor_profile_id'], unique=False)
    op.create_table('doctor_availability',
    sa.Column('doctor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_availability_doctor_profile_id'), 'doctor_availability', ['doctor_profile_id'], unique=False)
    op.create_table('doctor_unavailability',
    sa.Column('doctor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('unavailable_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_unavailability_doctor_profile_id'), 'doctor_unavailability', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_doctor_unavailability_unavailable_date'), 'doctor_unavailability', ['unavailable_date'], unique=False)
    op.create_table('lab_links',
    sa.Column('doctor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_id', sa.Uuid(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['smile_simulations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_links_doctor_profile_id'), 'lab_links', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_lab_links_simulation_id'), 'lab_links', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_lab_links_token'), 'lab_links', ['token'], unique=True)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('staff_invites',
    sa.Column('doctor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_invites_doctor_profile_id'), 'staff_invites', ['doctor_profile_id'], unique=False)
    op.create_table('staff_members',
    sa.Column('doctor_profile_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='staffstatus'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_members_doctor_profile_id'), 'staff_members', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_staff_members_email'), 'staff_members', ['email'], unique=False)
    op.create_index(op.f('ix_staff_members_status'), 'staff_members', ['status'], unique=False)
    op.create_index(op.f('ix_staff_members_user_id'), 'staff_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_members_user_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_status'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_email'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_doctor_profile_id'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_staff_invites_doctor_profile_id'), table_name='staff_invites')
    op.drop_table('staff_invites')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_lab_links_token'), table_name='lab_links')
    op.drop_index(op.f('ix_lab_links_simulation_id'), table_name='lab_links')
    op.drop_index(op.f('ix_lab_links_doctor_profile_id'), table_name='lab_links')
    op.drop_table('lab_links')
    op.drop_index(op.f('ix_doctor_unavailability_unavailable_date'), table_name='doctor_unavailability')
    op.drop_index(op.f('ix_doctor_unavailability_doctor_profile_id'), table_name='doctor_unavailability')
    op.drop_table('doctor_unavailability')
    op.drop_index(op.f('ix_doctor_availability_doctor_profile_id'), table_name='doctor_availability')
    op.drop_table('doctor_availability')
    op.drop_index(op.f('ix_clinics_doctor_profile_id'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index(op.f('ix_billing_transactions_user_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_subscription_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_stripe_payment_intent_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_stripe_invoice_id'), table_name='billing_transactions')
    op.drop_index(op.f('ix_billing_transactions_status'), table_name='billing_transactions')
    op.drop_table('billing_transactions')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_smile_simulations_user_id'), table_name='smile_simulations')
    op.drop_index(op.f('ix_smile_simulations_status'), table_name='smile_simulations')
    op.drop_index(op.f('ix_smile_simulations_created_by_doctor_id'), table_name='smile_simulations')
    op.drop_table('smile_simulations')
    op.drop_index(op.f('ix_refresh_token_sessions_user_id'), table_name='refresh_token_sessions')
    op.drop_index(op.f('ix_refresh_token_sessions_token_hash'), table_name='refresh_token_sessions')
    op.drop_table('refresh_token_sessions')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_stripe_payment_method_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_is_default'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_password_reset_token_sessions_user_id'), table_name='password_reset_token_sessions')
    op.drop_index(op.f('ix_password_reset_token_sessions_token_hash'), table_name='password_reset_token_sessions')
    op.drop_table('password_reset_token_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_role'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_documents_patient_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_doctor_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_doctor_patients_patient_user_id'), table_name='doctor_patients')
    op.drop_index(op.f('ix_doctor_patients_doctor_user_id'), table_name='doctor_patients')
    op.drop_table('doctor_patients')
    op.drop_index(op.f('ix_conversations_patient_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_doctor_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_consultation_appointments_status'), table_name='consultation_appointments')
    op.drop_index(op.f('ix_consultation_appointments_patient_user_id'), table_name='consultation_appointments')
    op.drop_index(op.f('ix_consultation_appointments_owner_user_id'), table_name='consultation_appointments')
    op.drop_index(op.f('ix_consultation_appointments_doctor_user_id'), table_name='consultation_appointments')
    op.drop_table('consultation_appointments')
    op.drop_index(op.f('ix_user_accounts_role'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.drop_table('user_accounts')
    # ### end Alembic commands ###
