"""sync model drift

Revision ID: 21d3a9979721
Revises: 2d2f6d1d2bc2
Create Date: 2026-08-05 12:27:33.431127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21d3a9979721'
down_revision: Union[str, None] = '2d2f6d1d2bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinics', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this clinic is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('onboarding_sessions', sa.Column('staged_data', sa.JSON(), nullable=True))
    op.add_column('onboarding_sessions', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.alter_column('smile_simulations', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('subscriptions', sa.Column('extra_clinics_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('subscriptions', sa.Column('extra_staffs_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'extra_staffs_count')
    op.drop_column('subscriptions', 'extra_clinics_count')
    op.alter_column('smile_simulations', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('onboarding_sessions', 'stripe_customer_id')
    op.drop_column('onboarding_sessions', 'staged_data')
    op.alter_column('clinics', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this clinic is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_billing_transactions_external_transaction_id'), table_name='billing_transactions')
    op.drop_column('billing_transactions', 'external_transaction_id')
    # ### end Alembic commands ###
