"""Add profile fields to DoctorProfile

Revision ID: 2f4bd20eb42a
Revises: bac0c495212c
Create Date: 2026-04-28 03:56:12.536483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2f4bd20eb42a'
down_revision: Union[str, None] = 'bac0c495212c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('specialty', sa.String(length=255), nullable=True))
    op.add_column('doctor_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_profiles', 'contact_phone')
    op.drop_column('doctor_profiles', 'bio')
    op.drop_column('doctor_profiles', 'specialty')
    # ### end Alembic commands ###
