"""add_clinic_dashboard_fields

Revision ID: 3f4c30963427
Revises: aa0751bd86f6
Create Date: 2026-06-03 16:38:15.799117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f4c30963427'
down_revision: Union[str, None] = 'aa0751bd86f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_staff_assignments',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('staff_member_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary_clinic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_staff_assignments_clinic_id'), 'clinic_staff_assignments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_staff_assignments_staff_member_id'), 'clinic_staff_assignments', ['staff_member_id'], unique=False)
    op.create_table('staff_credits',
    sa.Column('staff_member_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_credits_clinic_id'), 'staff_credits', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_staff_credits_staff_member_id'), 'staff_credits', ['staff_member_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('staff_member_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True, comment='Clinic context for the transaction'),
    sa.Column('simulation_id', sa.Uuid(), nullable=True, comment='Simulation that triggered the deduction (if applicable)'),
    sa.Column('transaction_type', sa.Enum('INITIAL', 'PURCHASE', 'SIMULATION_USAGE', 'REFUND', 'ADJUSTMENT', name='credittransactiontype'), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False, comment='Change in credits: positive for additions, negative for deductions'),
    sa.Column('balance_after', sa.Integer(), nullable=False, comment="Staff member's credit balance after this transaction"),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='Human-readable reason for the transaction'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_id'], ['smile_simulations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_clinic_id'), 'credit_transactions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_simulation_id'), 'credit_transactions', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_staff_member_id'), 'credit_transactions', ['staff_member_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_transaction_type'), 'credit_transactions', ['transaction_type'], unique=False)
    op.drop_constraint(op.f('affiliates_code_key'), 'affiliates', type_='unique')
    op.drop_constraint(op.f('affiliates_user_id_key'), 'affiliates', type_='unique')
    op.drop_index(op.f('ix_affiliates_code'), table_name='affiliates')
    op.create_index(op.f('ix_affiliates_code'), 'affiliates', ['code'], unique=True)
    op.drop_index(op.f('ix_affiliates_user_id'), table_name='affiliates')
    op.create_index(op.f('ix_affiliates_user_id'), 'affiliates', ['user_id'], unique=True)
    op.create_index(op.f('ix_lab_links_patient_user_id'), 'lab_links', ['patient_user_id'], unique=False)
    op.add_column('smile_simulations', sa.Column('clinic_id', sa.Uuid(), nullable=True, comment='Clinic this simulation belongs to'))
    op.add_column('smile_simulations', sa.Column('created_by_staff_id', sa.Uuid(), nullable=True, comment='Staff member who created this simulation (if applicable)'))
    op.alter_column('smile_simulations', 'lab_link_label',
               existing_type=sa.VARCHAR(length=255),
               comment='Optional label for lab/link reference',
               existing_nullable=True)
    op.create_index(op.f('ix_smile_simulations_clinic_id'), 'smile_simulations', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_smile_simulations_created_by_staff_id'), 'smile_simulations', ['created_by_staff_id'], unique=False)
    op.create_foreign_key(None, 'smile_simulations', 'staff_members', ['created_by_staff_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'smile_simulations', 'clinics', ['clinic_id'], ['id'], ondelete='SET NULL')
    op.drop_column('smile_simulations', 'credit_deducted')
    op.add_column('staff_members', sa.Column('credit_balance', sa.Integer(), nullable=False, server_default='0', comment='Number of simulation credits available to this staff member'))
    op.add_column('staff_members', sa.Column('primary_clinic_id', sa.Uuid(), nullable=True, comment='Primary clinic this staff member is assigned to'))
    op.create_index(op.f('ix_staff_members_primary_clinic_id'), 'staff_members', ['primary_clinic_id'], unique=False)
    op.create_foreign_key(None, 'staff_members', 'clinics', ['primary_clinic_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_subscriptions_stripe_checkout_session_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'stripe_checkout_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_checkout_session_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_subscriptions_stripe_checkout_session_id'), 'subscriptions', ['stripe_checkout_session_id'], unique=False)
    op.drop_constraint(None, 'staff_members', type_='foreignkey')
    op.drop_index(op.f('ix_staff_members_primary_clinic_id'), table_name='staff_members')
    op.drop_column('staff_members', 'primary_clinic_id')
    op.drop_column('staff_members', 'credit_balance')
    op.add_column('smile_simulations', sa.Column('credit_deducted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'smile_simulations', type_='foreignkey')
    op.drop_constraint(None, 'smile_simulations', type_='foreignkey')
    op.drop_index(op.f('ix_smile_simulations_created_by_staff_id'), table_name='smile_simulations')
    op.drop_index(op.f('ix_smile_simulations_clinic_id'), table_name='smile_simulations')
    op.alter_column('smile_simulations', 'lab_link_label',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Optional label for lab/link reference',
               existing_nullable=True)
    op.drop_column('smile_simulations', 'created_by_staff_id')
    op.drop_column('smile_simulations', 'clinic_id')
    op.drop_index(op.f('ix_lab_links_patient_user_id'), table_name='lab_links')
    op.drop_index(op.f('ix_affiliates_user_id'), table_name='affiliates')
    op.create_index(op.f('ix_affiliates_user_id'), 'affiliates', ['user_id'], unique=False)
    op.drop_index(op.f('ix_affiliates_code'), table_name='affiliates')
    op.create_index(op.f('ix_affiliates_code'), 'affiliates', ['code'], unique=False)
    op.create_unique_constraint(op.f('affiliates_user_id_key'), 'affiliates', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('affiliates_code_key'), 'affiliates', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_credit_transactions_transaction_type'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_staff_member_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_simulation_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_clinic_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_staff_credits_staff_member_id'), table_name='staff_credits')
    op.drop_index(op.f('ix_staff_credits_clinic_id'), table_name='staff_credits')
    op.drop_table('staff_credits')
    op.drop_index(op.f('ix_clinic_staff_assignments_staff_member_id'), table_name='clinic_staff_assignments')
    op.drop_index(op.f('ix_clinic_staff_assignments_clinic_id'), table_name='clinic_staff_assignments')
    op.drop_table('clinic_staff_assignments')
    # ### end Alembic commands ###
