"""add gif_path to smile_simulations

Revision ID: 706ee3ba6995
Revises: d1c63314e57f
Create Date: 2026-04-17 01:47:23.834557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '706ee3ba6995'
down_revision: Union[str, None] = 'd1c63314e57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smile_simulations', sa.Column('gif_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smile_simulations', 'gif_path')
    # ### end Alembic commands ###
