"""add video_path to smile_simulations

Revision ID: bac0c495212c
Revises: 706ee3ba6995
Create Date: 2026-04-17 04:13:34.577707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bac0c495212c'
down_revision: Union[str, None] = '706ee3ba6995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smile_simulations', sa.Column('video_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smile_simulations', 'video_path')
    # ### end Alembic commands ###
