"""Add multi-view image fields to SmileSimulation

Revision ID: d1c63314e57f
Revises: 09315c06bdc6
Create Date: 2026-04-16 02:46:41.308137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1c63314e57f'
down_revision: Union[str, None] = '09315c06bdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smile_simulations', sa.Column('front_view_path', sa.Text(), nullable=True))
    op.add_column('smile_simulations', sa.Column('left_view_path', sa.Text(), nullable=True))
    op.add_column('smile_simulations', sa.Column('right_view_path', sa.Text(), nullable=True))
    op.add_column('smile_simulations', sa.Column('retractor_view_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smile_simulations', 'retractor_view_path')
    op.drop_column('smile_simulations', 'right_view_path')
    op.drop_column('smile_simulations', 'left_view_path')
    op.drop_column('smile_simulations', 'front_view_path')
    # ### end Alembic commands ###
